severity: low
exclude:
  - message: Giphy links
    pattern: media\.giphy\.com

  - message: Shield links
    pattern: img\.shields\.io

  - message: Codacy references
    pattern: "codacy_id:"

  - message: Local postgres environment
    pattern: postgresql://user:password@localhost:5432/db

  - message: Dependencies
    paths:
      - node_modules
      - venv

  - message: Tooling outputs
    paths:
      - coverage
      - docs/dist
      - package-lock.json
      - yarn-error.log
      - yarn.lock
