name: Install
description: Install dependencies

inputs:
  node-version:
    description: Node version
    default: "18"

runs:
  using: composite
  steps:
    - name: Checkout the source code
      uses: actions/checkout@v4

    - name: Enable corepack
      shell: bash
      run: corepack enable

    - name: Set the node version
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: yarn

    - name: Install yarn dependencies
      shell: bash
      run: yarn install --immutable

    - name: Install trufflehog3
      shell: bash
      run: pip install trufflehog3
