name: Install
description: Install dependencies

inputs:
  node-version:
    description: Node version
    default: "18"

runs:
  using: composite
  steps:
    - name: Checkout the source code
      uses: actions/checkout@v3

    - name: Fetch yarn's cache directory path
      id: yarn-cache-dir-path
      shell: bash
      run: echo "YARN_CACHE_DIR=$(yarn cache dir)" >> $GITHUB_ENV

    - name: Set up yarn package caching
      uses: actions/cache@v3
      id: yarn-cache
      with:
        path: ${{ env.YARN_CACHE_DIR }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Set the node version
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install node dependencies
      shell: bash
      run: yarn install --frozen-lockfile
